# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/rename.rb.tmpl in the rename repo.
class Rename < Formula
  desc "Recursive in-place search/replace with a typo-fixing mode"
  homepage "https://github.com/simonski/rename"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/rename-v0.1.5/rename_0.1.5_darwin_arm64.tar.gz"
      sha256 "bec63338b7fb18eb244d3e6fc453a784ba0d54ab87d04c531975d5a5697688b7"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/rename-v0.1.5/rename_0.1.5_darwin_amd64.tar.gz"
      sha256 "b7080b61accf4f9b0010592cfa4e67169ab9f9ae38f88123027e41f24fec84b5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/rename-v0.1.5/rename_0.1.5_linux_arm64.tar.gz"
      sha256 "2bfd3a696a204bbb20be75ea8ef929bfcb1bc848d423968cfa23dd5b25b5e8e7"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/rename-v0.1.5/rename_0.1.5_linux_amd64.tar.gz"
      sha256 "1aeb686e178b184be575bd9d15a1ab5e7e4cb7f0260739b580b05af07e215f79"
    end
  end

  def install
    bin.install "rename"
  end

  test do
    assert_match "0.1.5", shell_output("#{bin}/rename version")
  end
end
