# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/rename.rb.tmpl in the rename repo.
class Rename < Formula
  desc "Recursive in-place search/replace with a typo-fixing mode"
  homepage "https://github.com/simonski/rename"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/rename-v0.1.2/rename_0.1.2_darwin_arm64.tar.gz"
      sha256 "f06c9eb1d87eeda195969c9c9ad0e3aca27c514ccf43226697538e26206dd128"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/rename-v0.1.2/rename_0.1.2_darwin_amd64.tar.gz"
      sha256 "b249ab3623a16a459baface36a41ffd13c4d760f5b708f051375ac2de55cee49"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/rename-v0.1.2/rename_0.1.2_linux_arm64.tar.gz"
      sha256 "191dabffba90b0c36cafc5e5cc8b7f43e9677a40f6d4c3d3c028fa0c930ad9ff"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/rename-v0.1.2/rename_0.1.2_linux_amd64.tar.gz"
      sha256 "af50be63444b81fa94f112b46deb527b05861299befe7055fbc9dba5f4b6e1bb"
    end
  end

  def install
    bin.install "rename"
  end

  test do
    assert_match "0.1.2", shell_output("#{bin}/rename version")
  end
end
